### ISSUE TITLE
Custom crosshair working but doesn't change colors on hit.

### ISSUE THREAD

**Issue by Dedbul** [Vexcenot/-Middle-Mann#100]
**Describe the Issue**
Crosshair doesn't change its color on hit even tho i changed settings files.

**To Reproduce (gamemode/loadout etc)**
1. Remove "//" from "crosshair_animation.txt".
```
Animate "CustomCrosshair"		FgColor     "255 0 0 255"			Linear 	0.0 	0.00001
Animate "CustomCrosshair"		FgColor     "0 255 100 255"		Linear 	0.10 	0.10001
```
2. Use these settings in "crosshair.res" 
```
"visible" "1"
"labelText" "~" (tried several others and it still doesn't work)
"font" "Size:15 | ON"
"xpos" "cs-0.5"
"ypos" "cs-0.4999"
"fgcolor" "0 255 100 255"
```

**Expected behavior**
Crosshair should change its color to red on hit and then back to green

**Screenshots**
![image](https://github.com/Vexcenot/-Middle-Mann/assets/136989135/d32adff5-2101-4383-bd0a-835b2cf93261)
![image](https://github.com/Vexcenot/-Middle-Mann/assets/136989135/b159d651-a830-4deb-a44f-3027641ca2b7)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Resolution (Aspect Ratio): 16:9

**TF2 Specific Info (please complete the following information):**
 - HUD Version (either commit # or release version): 15.1.2
 - Customizations Applied (if any): No player image, Using built in hud custom crosshairs.
 - Other Mods (only applies if you have mods in `tf/custom`): mastercomfig, CastingEssentialsRed, Animated Loading Screen.

**Comment by TechnoSL** [comment]
managed to recreate, although i don't see why it isn't working. ideally it should just flash the crosshair on damage

will see if i can manage a fix (i never really tested the flashing either way but it might be a side effect from #35)

**Comment by TechnoSL** [comment]
mind redownloading (and remaking every setting) to see if it's fixed? thanks: https://github.com/TechnoSL/Middle-Mann/archive/refs/heads/master.zip

**Comment by Dedbul** [comment]
Yep, now it works. Big thx!
