### ISSUE TITLE
Low health coloration persists after death

### ISSUE THREAD

**Issue by TheBeanPolice** [Vexcenot/-Middle-Mann#102]
It's not uncommon for your health value to stay tinted red after you've died and respawned.

**Steps to reproduce the behavior**
1. Die a few times, probably while at low health
3. Respawn
4. See Issue

**Expected behavior**
I'd expect you health coloration to reset normally.

**Screenshots**
![bananabug](https://github.com/Vexcenot/-Middle-Mann/assets/143982870/35ab6e3c-e66c-4614-ac92-fdac36dfab2d)

**Desktop**
 - OS: Windows 10
 - Aspect Ratio: 1920x1080

**TF2 Specific Info**
 - HUD Version: v15.1.2 and previous versions.
 - Customizations Applied: None.
 - Other Mods: None.

**Comment by TechnoSL** [comment]
unfixable bug, every hud has this.

do hud_reloadscheme to fix it once it happens.
