### ISSUE TITLE
tf2 overlay health need FIX!

### ISSUE THREAD

**Issue by LucasPro12345** [Vexcenot/-Middle-Mann#107]
weel,play cthis custom(ow healt warning lol)and WTF.this is not on all screen edges...FIX PLS(and like more quality[optional]
![20230914153343_1](https://github.com/Vexcenot/-Middle-Mann/assets/144953777/208d92ea-c093-493d-a851-1e308e2e2cac)

**Comment by TechnoSL** [comment]
seems to be working fine to me
