### ISSUE TITLE
ok...this @2.0v this to repair ow2 heart warning[WT...]

### ISSUE THREAD

**Issue by LucasPro12345** [Vexcenot/-Middle-Mann#108]
ok, look at the crap image on the right with a lot of FOCUS and... you don't even understand this problem, blind

(https://github.com/Vexcenot/-Middle-Mann/assets/144953777/952d73f0-3644-4a2c-bce2-337583d15fd6)

**Comment by TechnoSL** [comment]
image is empty, bug report is useless. arigathanks gozaimuch.
