### ISSUE TITLE
I cant play mvm as medic with this hud

### ISSUE THREAD

**Issue by whydoIextist** [Vexcenot/-Middle-Mann#109]
**Description**

when i want to play some boot camp as medic the game crashes

**How it happens**
1. queue up some boot camp
2. play medic with projectile shield
3. the game will crash usually during/before the first wave

**Desktop**
 - OS: windows 10
 - Resolution: 1440 x 900 (native)

**TF2 Specific Info:**
 - HUD Version (either commit # or release version): v152
 - Customizations Applied (if any): health warning on
 - Other Mods: Sound replacements for phlog and mannmelter, subtitles mod, costum crosshair

**Comment by TechnoSL** [comment]
can you try without any other mods just to make sure it's not the hud causing these issues?

**Comment by whydoIextist** [comment]
I've tested by removing the hud first and it allowed me to complete a full mission with 0 errors, also i think its medic specifically as i playtested with sniper and it didn't crash
