### ISSUE TITLE
PLR warning cart icon thingy idk

### ISSUE THREAD

**Issue by Vexcenot** [Vexcenot/-Middle-Mann#110]
Seen in Bonesaw. When the cart is near the end of the point the icon has a glowing outline. It's too beeg. could be on other maps

1. Go to 'plr bonesaw and push cart to end (might be caused by it's grind percentage mechanic)

**Expected behavior**
not look weird

**Screenshots**
![image](https://github.com/Vexcenot/-Middle-Mann/assets/65585248/6eb64a37-e1f1-4c5c-95f7-697e1eac7413)

**Desktop (please complete the following information):**
 - OS: windows
 - 1980x1080

**Comment by TechnoSL** [comment]
mate it's your own hud please fix it yourself

**Comment by halamix2** [comment]
Qulicky hacked together by playing on plr_hacksaw_event with 2560x1440 res:

```res
"EscortItemImageAlert"
		{
			"ControlName"	"ImagePanel"
			"fieldName"		"EscortItemImageAlert"	
			"xpos"			"1"
			"ypos"			"45"
			"zpos"			"0"
			"wide"			"50"
			"tall"			"24"
			"autoResize"	"0"
			"pinCorner"		"0"
			"visible"		"0"
			"enabled"		"1"
			"tabPosition"	"0"
			"labelText"		""
			"image"			"../hud/cart_alert"
			"scaleImage"	"1"
			
			"if_multiple_trains_bottom"
			{
				"xpos"		"-5"
				"ypos"		"75"
			}
		}
```
