### ISSUE TITLE
Zombie Invasion Timer being undefined

### ISSUE THREAD

**Issue by LinkMarioKirby** [Vexcenot/-Middle-Mann#111]
**Describe the Issue**
ZI timers for abilities are marked by weird (kinda dev like idk) text instead of numbers

**To Reproduce (gamemode/loadout etc)**
1. Go to any ZI map and play as a zombie with an ability, then fire the thing that has the cooldown

**Expected behavior**
Have numbers instead of text

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Win 10
 - Resolution (Aspect Ratio): 1366x768

**TF2 Specific Info (please complete the following information):**
 - HUD Version (either commit # or release version): Commit [f40e83a](https://github.com/Vexcenot/-Middle-Mann/commit/f40e83abc0febc44e49e75511bf725cc519d34e6)
 - Customizations Applied (if any): Side Mann, all that jazz
 - Other Mods (only applies if you have mods in `tf/custom`): No

**Comment by TechnoSL** [comment]
vscript gamemode so its broken on every hud lolw 
probably something to do with language files so ill put this on low priority

**Comment by TechnoSL** [comment]
seems to have been fixed as of [the october 13, 2023 update](https://www.teamfortress.com/post.php?id=210711) so i'll close this now
