### ISSUE TITLE
ConTracker is not Opening

### ISSUE THREAD

**Issue by LinkMarioKirby** [Vexcenot/-Middle-Mann#112]
**Describe the Issue**
The ConTracker menu is not opening at all whatsoever, even after game restarts 

**To Reproduce (gamemode/loadout etc)**
Open the ConTracker, then nothing displays on the menu

**Expected behavior**
Actually show the ConTracker menu 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Resolution (Aspect Ratio): 1366x768

**TF2 Specific Info (please complete the following information):**
 - HUD Version (either commit # or release version): Commit [f40e83a](https://github.com/Vexcenot/-Middle-Mann/commit/f40e83abc0febc44e49e75511bf725cc519d34e6)
 - Customizations Applied (if any): Side-Mann
 - Other Mods (only applies if you have mods in `tf/custom`): No, hahahah

**Comment by LinkMarioKirby** [comment]
Redownloaded and it fixed it self

**Comment by LinkMarioKirby** [comment]
Broke after reopening the game

**Comment by TechnoSL** [comment]
you can always try binding some key to "show_quest_log" if the contracker button isnt working

**Comment by LinkMarioKirby** [comment]
i tired that, it just shows nothing on the contracker

**Comment by TechnoSL** [comment]
if so, i have no clue, the contracker honestly shouldn't even break since it still uses the default files + i can't recreate the bug at all even as much as i try [(here's me opening the contracker just fine on the latest commit](https://streamable.com/m1swr7)

might be due to resolution? try checking if 1280x720 makes the contracker work and if not then i'm all out of ideas

**Comment by LinkMarioKirby** [comment]
alright i shall try that

**Comment by LinkMarioKirby** [comment]
It didn't work, I think it might be some mods I have but I will get back to you on that
The mod that I suspect that is causing the problem is Modern Casual Preloader

**Comment by LinkMarioKirby** [comment]
here is all the mods 
![image](https://github.com/Vexcenot/-Middle-Mann/assets/147571847/2a762c8a-d2fa-49e2-9df8-5d8a74662409)
i don't know what else to say it no work :(

**Comment by TechnoSL** [comment]
try rermoving any mods that mess with hud files, master hitmarkers is a good start since it's very unstable atm

**Comment by LinkMarioKirby** [comment]
ok

**Comment by LinkMarioKirby** [comment]
That fixed it, Thanks!
