### ISSUE TITLE
%item_ad_text% is being displayed instead of description and price of the item

### ISSUE THREAD

**Issue by ailurophilly** [Vexcenot/-Middle-Mann#113]
**Describe the Issue**
%item_ad_text% is being displayed under featured

**To Reproduce (gamemode/loadout etc)**
Start a game

**Expected behavior**
A price and description of item should be displayed

**Screenshots**
Middle Mann
![image](https://github.com/Vexcenot/-Middle-Mann/assets/147918554/f38da30d-a8ae-4794-9a0f-95aa5ca5a519)

Default HUD
![image](https://github.com/Vexcenot/-Middle-Mann/assets/147918554/50f54d81-6231-42b4-a085-2ad30de1cf24)

**Desktop (please complete the following information):**
 - OS: Fedora Linux 39
 - Resolution (Aspect Ratio): 1920x1080 16:9

**TF2 Specific Info (please complete the following information):**
 - HUD Version (either commit # or release version): f40e83abc0febc44e49e75511bf725cc519d34e6
 - Customizations Applied (if any): none
 - Other Mods (only applies if you have mods in `tf/custom`): none

**Comment by TechnoSL** [comment]
vexcenot broke it for no reason so download this version of mainmenuoverride.res and overwrite the current file https://github.com/Vexcenot/-Middle-Mann/blob/014745d1315507165cbec3b6382e63f9df2c3ac9/resource/ui/mainmenuoverride.res
