### ISSUE TITLE
missing health, elements off screen

### ISSUE THREAD

**Issue by nuclearwar1000** [Vexcenot/-Middle-Mann#119]
** Fill these checkmarks before reporting a bug!**
- [*] i am not using any additional mods that might overwrite any hud files (things like portraits and stuff of the sort)

**Describe the Issue**
hi, im having some strange issues. my chat box is now partially off screen, and so are my kill notifications, and my health box disappears at resolutions above 1900x1200. i dont have any other mods aside from mastercomfig 

**To Reproduce (gamemode/loadout etc)**
1.open tf2
2.join game
3.observe chat
for the health bar, 
1.join game
2. set resolution to above 1900x1200
3. health bar and numbers now missing from the hud
**Expected behavior**
properly aligned chat and kill notifications and a present health bar regardless of resolution

**Screenshots**
![20231222172334_1](https://github.com/Vexcenot/-Middle-Mann/assets/28682179/dbc2d731-4fbf-49f4-9df9-94fc8fdf8329)
![20231222172409_1](https://github.com/Vexcenot/-Middle-Mann/assets/28682179/9184797c-987a-40da-9639-6d690113a89c)

**Desktop (please complete the following information):**
 - OS: win 11
 - Resolution 2560x1600 (1900x1200 in game) 16:10):

**TF2 Specific Info (please complete the following information):**
 - HUD Version (either commit # or release version): v18.2
 - Customizations Applied (if any, if none type "none"): none
 - Other Mods in tf/custom? if so, which ones?: mastercomfig

**Comment by nuclearwar1000** [comment]
I'll try it now! Good timing haha. Just looked at the changes, seems
exciting!

**Comment by nuclearwar1000** [comment]
Trying it now, text bleeding off screen isn't an issue anymore! But at the
higher resolution it still makes my health disappear, at the end of the day
I like 1900x1200 tho so for me case it could be worse! New class select and
menu n stuff looks great !

**Comment by Vexcenot** [comment]
Glad ye like it!

At high resolutions do you mean by changing from 1900x1200 to something greater? (e.g 1920x1080)

Doing that without restarting the game first could cause some issues could cause some issues. 

Could you send a screenshot of this issue happening?

**Comment by nuclearwar1000** [comment]
I could do that soon! Although I will say it looks pretty much the same as
the last screenshot I provided of the missing health, minus the text bleed
issue. I only experimented with resolutions in my native aspect ratio, so
I'll have to try 1920x1080 and see if that works or not, but I know that
the 2k 16:10 seems to be somewhat finicky.

**Comment by TechnoSL** [comment]
closing this as it's fixed as of #123

**Comment by nuclearwar1000** [comment]
Mmk! Awesome
