### ISSUE TITLE
Missing health at 4K resolution

### ISSUE THREAD

**Issue by Zadrave** [Vexcenot/-Middle-Mann#123]
** Fill these checkmarks before reporting a bug!**
- [] i am not using any additional mods that might overwrite any hud files (things like portraits and stuff of the sort)

**Describe the Issue**
My health bar is missing at 4K resolution.

**To Reproduce (gamemode/loadout etc)**
1. Go into the game
2. Join server
3. Look at health bar
4. See Issue

**Expected behavior**
Seeing the health bar

**Screenshots**
![image](https://github.com/Vexcenot/-Middle-Mann/assets/88107721/8e6f5d1b-990d-43fd-a6e0-968f314d3f68)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Resolution - 3840 x 2160 (16:9)

**TF2 Specific Info (please complete the following information):**
 - HUD Version (either commit # or release version): v19.1.1
 - Customizations Applied (if any, if none type "none"): none
 - Other Mods in tf/custom? if so, which ones?: Tested with nothing else

**Comment by TechnoSL** [comment]
i would try to recreate this but i don't own a 4k monitor. sorry.

**Comment by reyaaaaaaaa** [comment]
hey, i'm having the same issue. i'll attach some screenshots in 1920x1080, 2560x1440 and 3840x2160 (in that order)
it seems 3840x2160 is the only resolution (maybe higher) with this issue.
![Screenshot 2024-02-10 105304](https://github.com/Vexcenot/-Middle-Mann/assets/159620854/e6cf28b3-2f57-4d61-8f70-efcafb4c92ce)
![Screenshot 2024-02-10 105330](https://github.com/Vexcenot/-Middle-Mann/assets/159620854/2e65e272-9f02-4054-aadc-58433072724c)
![Screenshot 2024-02-10 105416](https://github.com/Vexcenot/-Middle-Mann/assets/159620854/f359e46b-44a2-4355-9ba8-7458bc945d3c)

**Comment by TechnoSL** [comment]
still can't recreate it due to the reasons above (dont own a 4k monitor), can you please change the wide/tall values in this file to f0 and check if it appears again? might be a theory https://github.com/Vexcenot/-Middle-Mann/blob/master/resource/ui/hudplayerhealth.res#L13-L14

**Comment by reyaaaaaaaa** [comment]
This has fixed the problem! Screenshots for reference, game screenshot taken in 3840x2160
![Screenshot 2024-02-10 201838](https://github.com/Vexcenot/-Middle-Mann/assets/159620854/820c42d2-224a-4ecb-9bbd-59c013245020)
![Screenshot 2024-02-10 202019](https://github.com/Vexcenot/-Middle-Mann/assets/159620854/1a28b0ce-61fe-49ba-8f9c-53c3b1af21f2)
