### ISSUE TITLE
Middle man hud and dyslexic crosshair won't work in game.

### ISSUE THREAD

**Issue by kohltic** [Vexcenot/-Middle-Mann#124]
- [] i am not using any additional mods that might overwrite any hud files (things like portraits and stuff of the sort)

**Describe the Issue**
I extracted the zip files into the custom folder in tf2 but in game it doesn't wanna show. They're not zip files, I haven't done anything with the custom folder or downloaded any other huds before. My crosshair is also set to none in game, trying just the crosshair wouldn't work too.

**To Reproduce (gamemode/loadout etc)**
2. Equip '...'
3. Play on '...'
4. See Issue
^ I'm not sure what this part means i'm sorry

**Expected behavior**
I followed everything In the tutorial video on how to install the hud/crosshair, I didn't delete/create anything just dragged the files to the tf2 custom folder and extracted them in there so I expected it to work but it didn't.

**Screenshots**
![Screenshot 2024-01-13 155503](https://github.com/Vexcenot/-Middle-Mann/assets/156527387/904ec895-b111-4ddb-9935-d124d93163e0)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Resolution (and Aspect Ratio, eg. 1280x960 4:3): 1920 x 1080, 16:9

**TF2 Specific Info (please complete the following information):**
 - HUD Version (either commit # or release version): v19.1.1
 - Customizations Applied (if any, if none type "none"): none
 - Other Mods in tf/custom? if so, which ones?: idk if this counts but the dyslexic crosshair other than that nothing

**Comment by TechnoSL** [comment]
we know, nothing we can do about it, bug vexcenot to fix dyslexic crosshairs.
