### ISSUE TITLE
Fonts are incorrect on linux

### ISSUE THREAD

**Issue by TheNeutralCat** [Vexcenot/-Middle-Mann#127]
- [x] i am not using any additional mods that might overwrite any hud files (things like portraits and stuff of the sort)

**Describe the Issue**
Fonts are incorrect (and look quite bad) when running TF2 on linux

**To Reproduce (gamemode/loadout etc)**
1. Use some kind of linux OS
2. Verify you have the proper fonts installed
3. Verify the fonts work in vanilla tf2
4. Install middle mann hud
:(

**Expected behavior**
Fonts are incorrect and differ from expected windows behavior very much. This sucks because the tf2's fonts work just fine with no mods installed whatsoever.

**Screenshots**
VANILLA TF2 (empty custom folder):
![Vanilla TF2](https://github.com/Vexcenot/-Middle-Mann/assets/89658725/c6fd4cad-8d76-4d1a-a447-14d761a70711)

MIDDLE MANN HUD:
![Middle Mann](https://github.com/Vexcenot/-Middle-Mann/assets/89658725/a514e3e3-e1da-4c8e-a8c2-638fbc425f8e)

VANILLA TF2 (empty custom folder):
![Vanilla TF2](https://github.com/Vexcenot/-Middle-Mann/assets/89658725/67a02e97-c2a3-4e44-9b62-dbadc16a329d)

MIDDLE MANN HUD:
![Middle Mann](https://github.com/Vexcenot/-Middle-Mann/assets/89658725/554228b5-3cd8-4426-8a9c-e9a2eda39fc2)

**Desktop:**
 - OS: Debian 12
 - Resolution: 1920x1080

**TF2 Specific Info:**
 - HUD Version: v21
 - Customizations Applied: none
 - Other Mods in tf/custom?: none

note: I was able to (kind of?) fix this by appending the "CustomFontFiles" section from the vanilla "sourcescheme.res" and "clientscheme.res" to the corresponding files inside Middle Mann Hud. however I don't know what I'm doing so and obviously that doesn't fix everything and it think it breaks other things too.

MY HACKY SOLUTION (with my custom folder full of other crap):
![20240421225938_1](https://github.com/Vexcenot/-Middle-Mann/assets/89658725/63062956-b615-418c-afc5-29cb389f2fd8)

**Comment by halamix2** [comment]
Redame says to install fonts included in the repo to your system; it works for me on Fedora:
![20240422214802_1](https://github.com/Vexcenot/-Middle-Mann/assets/5176598/c04d68aa-b8aa-4618-bffe-5bddccbb25ed)
