### ISSUE TITLE
chat and killfeed are cut off in 4:3

### ISSUE THREAD

**Issue by MairYote** [Vexcenot/-Middle-Mann#130]
**Fill these checkmarks before reporting a bug!**

- [] i am not using any additional mods that might overwrite any hud files (things like portraits and stuff of the sort)

**Describe the Issue**
A clear and concise description of what the Issue is.
-playing in match with 4:3 has the chat and killfeed appear partially off screen (cut off)(see screenshot)

**Steps To Reproduce (gamemode/loadout etc)**
Steps to reproduce the behavior: use 4:3

2. Equip '...'
3. Play on '...'
4. See Issue

**Expected behavior**

**Screenshots**

![20240527223846_1](https://github.com/Vexcenot/-Middle-Mann/assets/148646403/e92f5d5e-8080-46b7-a0de-bc6f9c19875c)

**Desktop (please complete the following information):**

- OS [e.g. Windows 10, macOS 11.5, Ubuntu 20.04]: Arch linux updated as of 28-05-2024 with KDE
- Resolution and Aspect Ratio [eg. 1280x960 4:3]: 4:3 with a variety of resolutions, no change found with any resolution selected

**TF2 Specific Info (please complete the following information):**

- HUD Version (either [commit #](https://i.imgur.com/Jx06jeZ.png) or release version): just installed, so most recent as of this report
- Customizations Applied (if any, if none type "none"): none (tried the ultrawide fix: didn't work)
- Other Mods in tf/custom? if so, which ones?: none

**Comment by TechnoSL** [comment]
er, it works fine on my end.... (4:3 1280x960)

are you absolutely sure it's not a linux-specific issue or anything? this is a clean copy of the hud i just downloaded working fine 

![20240530210030_1](https://github.com/Vexcenot/-Middle-Mann/assets/41777800/ff63c558-bc10-4ead-bf44-d05e4015e20c)

**Comment by MairYote** [comment]
I reinstalled twice and that fixed it lol. I've played for a day now with no issues. weird.

**Comment by TechnoSL** [comment]
great, closing issue as fixed then
