### ISSUE TITLE
[Feature Request] Q and E buttons to go back/forward/edit loadout

### ISSUE THREAD

**Issue by GOTHMONEY** [Vexcenot/-Middle-Mann#131]
Most modern HUDs (first one that comes to mind is[ voidhud](https://github.com/cjrose/voidHUD)) have this and I'd like for this one to have it too.

**Comment by tekunotri** [comment]
but we do have it, here's an example.

just because you cant see it doesent mean it's not there.

idk where else would you want these at

https://github.com/Vexcenot/-Middle-Mann/blob/720b500bdb6a59b8c480ed6bc37e9519ec4c9ea5/resource/ui/itemselectionpanel.res#L268-L285

**Comment by GOTHMONEY** [comment]
I can't press Q to leave the Loadout and Backpack menus.
![inventory](https://github.com/Vexcenot/-Middle-Mann/assets/91788386/76062b0d-76ea-4c05-a7fd-7d57e31d5f46)
![loadout](https://github.com/Vexcenot/-Middle-Mann/assets/91788386/c07af609-76c0-49fb-9ff3-ea91cbf0618b)

**Comment by tekunotri** [comment]
done, redownload the hud!
