### ISSUE TITLE
Issue with TF2 Style (Corners) Health & Ammo Positions

### ISSUE THREAD

**Issue by georgiesgithub** [Vexcenot/-Middle-Mann#133]
**Fill these checkmarks before reporting a bug!**

- [X] i am not using any additional mods that might overwrite any hud files (things like portraits and stuff of the sort)

**Describe the Issue**
The 2D playermodel portrait is located in the wrong location.

**Steps To Reproduce (gamemode/loadout etc)**

1. Use the TF2 Style (Corners) Health & Ammo Positions customization
2. Go into game and use the 2D playermodels rather than 3D
3. 2D playermodel icon appears at the top left of the screen

I tried again later using the On (Default) player model customization, and it moved it to another weird spot.

**Expected behavior**
2D Playermodel appears at the bottom left like the 3D playermodel does.

**Screenshots**
If applicable, add screenshots to help explain your problem.: https://imgur.com/a/clFfaVj

**Desktop (please complete the following information):**

- OS Windows 11
- Resolution and Aspect Ratio 1920x1080, 16:9

**TF2 Specific Info (please complete the following information):**

- HUD Version (either [commit #](https://i.imgur.com/Jx06jeZ.png) or release version): 22.0.1
- Customizations Applied (if any, if none type "none"): TF2 Style (Corners) Health & Ammo Positions
- Other Mods in tf/custom? if so, which ones?: Hitsounds, custom reload anims for pistols, sniper anim pack, medic anim pack, toon muzzle flashes, healing effects 2.0, griddy replacement for kazotsky

**Comment by tekunotri** [comment]
done
