### ISSUE TITLE
[Feature Request] Move Uber Percentage Above/Below/Inside of Uber Meter

### ISSUE THREAD

**Issue by georgiesgithub** [Vexcenot/-Middle-Mann#134]
**Is your feature request related to a problem? Please describe.**
*A clear and concise description of what the problem is. *
The Uber Percentage is at an awkward position. As a medic, you want that front and center. Close to the crosshair so you see it at all times.

**Describe the solution you'd like**
Please move the Uber Percentage inside/below/above the uber meter at the center of the screen.

**Additional context**
This is an amazing hud, just a small tweak like this goes miles into making it the perfect hud,

**Comment by georgiesgithub** [comment]
Here's an example of what I'm talking about. This is from improved default hud.
https://static.tf2huds.dev/Improved-default-HUD/img/7e3e18ee-9ca1-4f7d-bd7c-7ede239fe216.png

**Comment by tekunotri** [comment]
will probably think about it (maybe), for now just add this to hudmediccharge.res and move the `xpos` and `ypos` around until you're satisfied

```
	//==================================================================================================================================================
	// UNDER CROSSHAIR SMALL UBER PERCENTAGE
	//==================================================================================================================================================
	"ChargeLabel"
	{
		"ControlName"								"CExLabel"
		"fieldName"									"ChargeLabel"
		"xpos"										"cs-0.5" // move this as you see fit
		"ypos"										"c9" // move this as you see fit
		"zpos"										"2"
		"wide"										"100"
		"tall"										"20"
		"visible"									"1"
		"enabled"									"1"
		"proportionaltoparent"						"1"
		"labelText"									"#TF_UberchargeMinHUD"
		"textAlignment"								"center"
		"font"										"HudFontMedium" // check mm_fonts to see what you can change this into
		"fgcolor"									"0 255 255 255" // eye-catching color

	}```
