### ISSUE TITLE
Team Painted Cosmetics not Properly Showing Blu Version in Class Customization

### ISSUE THREAD

**Issue by MerrytheManokit** [Vexcenot/-Middle-Mann#135]
**Fill these checkmarks before reporting a bug!**

- [X] i am not using any additional mods that might overwrite any hud files (things like portraits and stuff of the sort)

**Describe the Issue**
When using a cosmetic with a team color only the red team's version of the cosmetic shows in the class customization menu. However ive only tested this with the Value of Teamwork on the Head Prize since i currently have no other team painted cosmetics.

**Steps To Reproduce (gamemode/loadout etc)**

1. Equip a cosmetic with a team paint on it
2. Swap to Blu team preview
3. The cosmetic still shows the Red team version

**Expected behavior**
The preview should show the Blu team variant of the cosmetic.

**Screenshots**
![image](https://github.com/user-attachments/assets/42349ecc-621f-4e9d-b743-fe7fee3c33f9)
![image](https://github.com/user-attachments/assets/54795049-c978-4134-9842-b07eb6f7248c)
How the cosmetic is supposed to look:
![image](https://github.com/user-attachments/assets/2915ab8e-92db-43e1-bc0b-a70f9ca96d3d)

**Desktop (please complete the following information):**

- OS [e.g. Windows 10, macOS 11.5, Ubuntu 20.04]: Windows 11
- Resolution and Aspect Ratio [eg. 1280x960 4:3]: 1920x1080 16:9

**TF2 Specific Info (please complete the following information):**

- HUD Version (either [commit #](https://i.imgur.com/Jx06jeZ.png) or release version (click the console button in the main menu)): v22.0.2
- Customizations Applied (if any, if none type "none"): None
- Other Mods in tf/custom? if so, which ones?: None

**Comment by MerrytheManokit** [comment]
In hindsight this probably isnt the HUD, but ill leave the report up just in case it is.

**Comment by tekunotri** [comment]
> In hindsight this probably isnt the HUD, but ill leave the report up just in case it is.

it isn't. closing this.
