### ISSUE TITLE
Bug- Adding charge meter for the Sniper "The Fortified Compound" Bow

### ISSUE THREAD

**Issue by DagNinja-Yair** [Vexcenot/-Middle-Mann#136]
**Fill these checkmarks before reporting a bug!**

- [] i am not using any additional mods that might overwrite any hud files (things like portraits and stuff of the sort)

**Describe the Issue**
There power bar of "The Fortifies Compound" that exists in the default version of tf2  doesn't appear in your HUD, it's important to know how much damage your arrrow is gonna inflict.

**Steps To Reproduce (gamemode/loadout etc)**

1. Go to a random match and play Sniper
2. Equip "The Fortified Compund" Bow
3. There is the ammow numbers but not the charging bar.

**Expected behavior**
See the charging bar somewhere bellow my ammo numbers, cause right now it's non-existent.

**Screenshots**
![The Fortified Compund BASIC](https://github.com/user-attachments/assets/dfe4b6ba-6cbc-4ded-ba5b-94e5a7828f8a)
![The Fortified Compund HUD BUG](https://github.com/user-attachments/assets/7973f6fd-5d59-49ff-a3c7-7b89a28650e8)

- OS Windows 10
- Resolution and Aspect Ratio: 1920*1080

**TF2 Specific Info (please complete the following information):**

- HUD Version "v22.0.2"
- Customizations Applied (if any, if none type "none"): none
- Other Mods in tf/custom? if so, which ones?: no other mods

**Comment by tekunotri** [comment]
it's there. you giving me ZERO screenshots of the hud itself and a screenshot of optive hud and default certainly won't help.

**Comment by DagNinja-Yair** [comment]
> it's there. the sniper bows use the same meter as the demoman's sticky charge. ![image](https://private-user-images.githubusercontent.com/41777800/356838627-b889b615-1ee3-4e19-a48b-9a0604ae9a5d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMzOTI0OTQsIm5iZiI6MTcyMzM5MjE5NCwicGF0aCI6Ii80MTc3NzgwMC8zNTY4Mzg2MjctYjg4OWI2MTUtMWVlMy00ZTE5LWE0OGItOWEwNjA0YWU5YTVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODExVDE2MDMxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThmNmUzMmI2ZjE4OGI2ODY3YTU1YTY5NzMzN2JlYjBhMjAwNmY5YmZiMTI5N2MwZTRhYTQzMDhhYWRmOTgwMjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.W08vrhf_BV1qleXFQzw1yYrjXvRKkBFZ9ZP_fq4sl_M)
> 
> you giving me ZERO screenshots of the hud itself and a screenshot of optive hud and default certainly won't help.

I attached ONE screenshot of the default tf2 hud and the SECOND screenshot is from your hud. I wasn't using the Huntsman, but was using "The Fortified Compund", which is a differenct bow of the sniper.

You can see in the second screenshot from your hud that the meter doesn't appear, it would be nice if it would appear, is there something I understand wrong about your comment? Is that not the screenshot of the hud itself? If you meant a code screenshot, I don't know where, just wanted to report that the bug is happening, that's why I sent a visual gameplay screenshot, so sorry for that misunderstanding. Do you think you can look for the cause for it?

**Comment by tekunotri** [comment]
thats awesome bro next time put a bug report in the [OPTIVE HUD github issues](https://github.com/tekunotri/optive-hud/issues/new) instead of this COMPLETELY unrelated hud.

it's also intentional. [notice how there's no demoman charge meter clip in this clip?](https://youtu.be/MPNLneePAwQ?si=g85pbd6mdlaHDEZ3&t=18)

closing!
