### ISSUE TITLE
Missing texture blocks vision when using transparent viewmodel setting

### ISSUE THREAD

**Issue by AlexJMGames** [Vexcenot/-Middle-Mann#141]
**Fill these checkmarks before reporting a bug!**

- [x] i am not using any additional mods that might overwrite any hud files (things like portraits and stuff of the sort)
Originally was using other mods, Disabled all of them entirely and clean installed MiddleMann, Issue persisted.

**Describe the Issue**
A clear and concise description of what the Issue is.
The pink/black checkered texture completely blocks vision ingame when the transparent viewmodel setting is enabled.

**Steps To Reproduce (gamemode/loadout etc)**
Steps to reproduce the behavior: Turn on transparent viewmodel. (Removing the "//" in it's .res and executing "hud_reloadscheme" in the console)

**Expected behavior**
Viewmodel should be translucent.

**Screenshots**

![20240902081126_1](https://github.com/user-attachments/assets/49849de0-3b47-4d54-b360-5e09b3ff9b9b)
![20240902081146_1](https://github.com/user-attachments/assets/97c33ae4-604c-4335-b308-a54411b368ed)
![20240902081200_1](https://github.com/user-attachments/assets/fc0cb093-361c-406f-89d9-8d8393d3755e)
![20240902081217_1](https://github.com/user-attachments/assets/09233de0-0ee0-43bd-be67-6a22b18a47bd)

**Desktop (please complete the following information):**

- OS [e.g. Windows 10, macOS 11.5, Ubuntu 20.04]: Windows 10Pro
- Resolution and Aspect Ratio [eg. 1280x960 4:3]: 1920x1080 16:9

**TF2 Specific Info (please complete the following information):**

- HUD Version (either [commit #](https://i.imgur.com/Jx06jeZ.png) or release version (click the console button in the main menu)): e443f7e 
- Customizations Applied (if any, if none type "none"):  none
- Other Mods in tf/custom? if so, which ones?: Originally Alaxe's female pyro mod and modern casual preloader

**Comment by ChildishGiant** [comment]
Oh this might be what caused my issue before actually #139

**Comment by tekunotri** [comment]
i knew i forgot to test something...

fixed as of https://github.com/Vexcenot/-Middle-Mann/commit/ca1c5fa14d6de7231c1edc0b1549c4b565f503e4
