### ISSUE TITLE
[Feature Request] Streamer Mode

### ISSUE THREAD

**Issue by ottergauze** [Vexcenot/-Middle-Mann#142]
**Is your feature request related to a problem? Please describe.**
The feature list on comfig.app/huds lists Streamer Mode as a feature of this HUD. I was a little disappointed to see that this doesn't seem to actually be a feature of the HUD. But it would be a feature I feel a lot of people would find useful.

**Describe the solution you'd like**
A customisation for Middle Man that allows for player names and avatars along the entire game's UI to be hidden, similarly to budhud. The in-game chat can now be disabled in Advanced Options, so this won't need to be changed.

**Additional context**
Any form of hiding player names would work. Some HUDs accomplish this by packaging in a font that replaces all characters with horizontal lines, some just remove the text entirely.

**Comment by tekunotri** [comment]
this gets a "maybe" at best from me, but i'm also a personal believer of "if someone REALLY wants to streamsnipe you, they can no matter the protections" so it's low priority

**Comment by ottergauze** [comment]
> this gets a "maybe" at best from me, but i'm also a personal believer of "if someone REALLY wants to streamsnipe you, they can no matter the protections" so it's low priority
> 
> also this hud never had streamer mode to begin with. blame vexcenot for setting that in the comfig tags.

That's true, but for me atleast I just prefer to play the game with names hidden. Spectator mode is just a more generic way to refer to it, I suppose. It's fair that it's low priority, though.

**Comment by tekunotri** [comment]
i got bored. feel free to test and if no major issues arise it'll be the next update. 
https://github.com/Vexcenot/-Middle-Mann/archive/refs/heads/streamermode.zip
