### ISSUE TITLE
GameBanana release is missing info.vdf

### ISSUE THREAD

**Issue by madbanana22** [Vexcenot/-Middle-Mann#144]
**Describe the Issue**
The GameBanana release is missing info.vdf, which makes it an invalid HUD.

**Steps To Reproduce (gamemode/loadout etc)**

1. download the latest release from gamebanana
2. install
3. cry why it doesnt work

**Expected behavior**
Have the file exist in the zip

**Screenshots**
![nE7ZA7Y8A0](https://github.com/user-attachments/assets/71c64cd6-30c8-4cac-8f98-282eb1763ca5)

**TF2 Specific Info (please complete the following information):**

- HUD Version: [-middle-mann_38379, hash 41554d97ae85ef180d581fed4526ed1d](https://gamebanana.com/mods/download/445578#FileInfo_1321097)

**Comment by Vexcenot** [comment]
hehe whoops
