### ISSUE TITLE
MvM Scoreboard overlapping text and player model cutoff

### ISSUE THREAD

**Issue by Quantum-Apple** [Vexcenot/-Middle-Mann#32]
Been playing on some mvm community servers and have noticed the server name and spectators overlapping with other elements of the hud. The player model shown on the scoreboard also gets cut off when it extends too far left. 

Text Overlap:
Noticed the overlapping text on the https://testing.potato.tf/ servers, but issue can likely be replicated on other mvm servers with a long enough name. Just join a server and go into spectator.

Player Model Cutoff:
Example screenshot showing the model being cut off is a demoman holding a necro smasher, although other classes can likely have the same issue with other weapon combinations.

Specs:
This was on Windows 11 with a 2560 x 1440 resolution.

![Screenshot (4)](https://github.com/Vexcenot/Middle-Mann/assets/141591941/85a64646-f808-4c8b-9e07-c601997fb7b7)
![Screenshot (5)](https://github.com/Vexcenot/Middle-Mann/assets/141591941/e82bc041-2f4a-4627-9160-862b1bae0d67)

**Comment by TechnoSL** [comment]
both of these are kinda hard fixes, server label will always break on a wave that's massive (aka w666 or some potato.tf missions) (see pic below)
![image](https://github.com/Vexcenot/-Middle-Mann/assets/41777800/ef22dd49-6e65-4511-ad50-b15feae1bc4a)

as for playermodel i'd have to rewrite the normal scoreboard itself, i'll think on how to do both of these.

**Comment by TechnoSL** [comment]
took a while, sorry!

would like some feedback on this before pushing it (i mostly removed backgrounds + changed some stuff around)
