### ISSUE TITLE
MvM Sapper Meter issues

### ISSUE THREAD

**Issue by Quantum-Apple** [Vexcenot/-Middle-Mann#36]
The mvm sapper meter text is black, compared to all the other meters which have white text. The meter bar itself ends really closely to the edge of the box containing the meter. Also, I'm not sure if the meter itself being in the bottom right corner is intentional instead of being closer to the center. 

This was on Windows 11 on 2560 x 1440

The top screenshot is with no sapper power upgraded, the bottom screenshot is with sapper power upgraded.

![Screenshot (14)](https://github.com/Vexcenot/-Middle-Mann/assets/141591941/1fe2e7da-0855-47b0-b3e3-94d33fb87cba)
![Screenshot (15)](https://github.com/Vexcenot/-Middle-Mann/assets/141591941/736dac5b-251e-4e18-a706-58c975396e91)

**Comment by TechnoSL** [comment]
that file never existed iirc, i'll fix it shortly

**Comment by TechnoSL** [comment]
ok it's fixed now, please redownload latest commit and let me know if it works on highe resolutions (i only tested 1280x720 and 1280x960)
