### ISSUE TITLE
MvM sapper meter overlaps with bomb icon

### ISSUE THREAD

**Issue by Quantum-Apple** [Vexcenot/-Middle-Mann#42]
The sapper meter in mvm overlaps with the bomb icon when the wave is active

Windows 11
2560 x 1440 

![Screenshot (17)](https://github.com/Vexcenot/-Middle-Mann/assets/141591941/57243ec9-6e10-4d72-a9f2-8df0a0278b33)

**Comment by TechnoSL** [comment]
i don't win at all do i

ill fix this later, for now go to `resource/ui/huditemeffectmeter_sapper.res` and change the ypos to move it, ill find a better place to move it since the last fix was kinda bandaid-y

**Comment by Quantum-Apple** [comment]
Possible solution to this would be to move the crit counter to the bottom, similarly to the engineer layout, and just have 3 other possible meters (cloak, spycicle, and sapper) above it.

![Screenshot (31)](https://github.com/Vexcenot/-Middle-Mann/assets/141591941/366e77ff-4aa3-4358-9ff8-d359bdbd27ad)
