### ISSUE TITLE
Target ID health cross off-center

### ISSUE THREAD

**Issue by Presto06** [Vexcenot/-Middle-Mann#47]
**Describe the Issue**
Target ID health cross off-center

**Screenshots**
![image](https://github.com/Vexcenot/-Middle-Mann/assets/123919000/b250a8ae-670b-4c02-9cb5-ff42c8ab6f57)

**Desktop (please complete the following information):**
 - OS:  Windows 11
 - Resolution: 2560x1440

**Comment by TechnoSL** [comment]
the cross is horrible to edit @Vexcenot can deal with it i never touched any of that

**Comment by TechnoSL** [comment]
ok i checked it, and i decided to make it less jarring.

![hl2_2023-08-19_05-28-57](https://github.com/Vexcenot/-Middle-Mann/assets/41777800/dbd223f0-ebba-4978-bee2-957dba94d4c9)
![hl2_2023-08-19_05-28-52](https://github.com/Vexcenot/-Middle-Mann/assets/41777800/862767ca-5051-4a95-bd31-e479ef461a16)
