### ISSUE TITLE
Gas Passer meter off center

### ISSUE THREAD

**Issue by Quantum-Apple** [Vexcenot/-Middle-Mann#49]
The gas passer meter is off center and overlaps with the phlog meter.

Windows 11
2560 x 1440

![Screenshot (20)](https://github.com/Vexcenot/-Middle-Mann/assets/141591941/d231da5e-f121-481e-a311-b23cf1cebc76)

**Comment by TechnoSL** [comment]
keeping this low priority, i'll try to remaster every single meter some day whenever i have time, keeping this low priority for now.
