### ISSUE TITLE
MvM Projectile Shield Meter Overlaps Ubercharge Bar

### ISSUE THREAD

**Issue by Quantum-Apple** [Vexcenot/-Middle-Mann#50]
The mvm projectile shield upgrade's meter overlaps with the ubercharge bar.

Windows 11
2560 x 1440

![Screenshot (19)](https://github.com/Vexcenot/-Middle-Mann/assets/141591941/dbb85ff9-217c-458a-a7bb-713987a6c5e6)

![Screenshot (26)](https://github.com/Vexcenot/-Middle-Mann/assets/141591941/9fbd788e-b565-44a1-bac3-8fab13605b6f)

**Comment by TechnoSL** [comment]
fyi: this fix will probably not be in the big "meter rewrites" as the medic shield charge meter is controlled by `huditemeffectmeter_scout.res`, wich also controls the scout's meters.

**Comment by Quantum-Apple** [comment]
I was able to fix this by changing the ypos around in a few res files, having only a slight overlap with the vaccinator resistance icons. I basically just swapped the positions of the scout primary and secondary meters. These are the values that worked for me on Windows 11 and a 2560x1440 resolution.

huditemeffectmeter_sodapopper.res - "ypos" "c102"
huditemeffectmeter_cleaver.res - "ypos" "c81"
huditemeffectmeter_scout.res - "ypos" "c81"


![Screenshot (39)](https://github.com/Vexcenot/-Middle-Mann/assets/141591941/596ba847-0d0d-42d9-8672-108d9695caaa)
![Screenshot (40)](https://github.com/Vexcenot/-Middle-Mann/assets/141591941/bcdbe026-655c-4035-bba8-0b4d0aec29c0)
![Screenshot (41)](https://github.com/Vexcenot/-Middle-Mann/assets/141591941/ecd169fc-3c7f-4882-9ef9-30149b2aa10f)
![Screenshot (42)](https://github.com/Vexcenot/-Middle-Mann/assets/141591941/edb79f1a-5ebc-42ea-bae8-ea8c540cc2b2)
