### ISSUE TITLE
Switching from shield to stickybomb launcher doesn't show sticky count

### ISSUE THREAD

**Issue by Quantum-Apple** [Vexcenot/-Middle-Mann#51]
When switching from a shield to a stickybomb launcher, the sticky bomb count doesn't immediately update. Instead, it just shows a blank box until a sticky is fired, updating the stickybomb count.

Windows 11
2560 x 1440

Tide Turner Equipped
![Screenshot (27)](https://github.com/Vexcenot/-Middle-Mann/assets/141591941/4d5817e7-d944-4f22-8b8e-1a12d62b9d45)

Switched to Sticky Jumper
![Screenshot (30)](https://github.com/Vexcenot/-Middle-Mann/assets/141591941/62d37ffd-4e53-420e-8448-4e3f3114420e)

Sticky fired
![Screenshot (29)](https://github.com/Vexcenot/-Middle-Mann/assets/141591941/3389618e-7972-4b39-b9c9-4050ab43116e)

**Comment by TechnoSL** [comment]
normal bug that happens on every hud, unfixable afaik.
