### ISSUE TITLE
Controller Taunt Menu Appears Off-Center and Mostly Off-Screen

### ISSUE THREAD

**Issue by LexHansenGuitar** [Vexcenot/-Middle-Mann#55]
**Describe the Issue**
When playing with a controller, the taunt menu appears off to the side and most of it can't be seen as it is off-screen.

**To Reproduce (gamemode/loadout etc)**
1. Connect a controller through Steam
2. Use Steam's default TF2 configuration or one based on it
3. Join a game
4. Hit g on the keyboard or open the taunt menu some other way
5. See Issue

**Screenshots**
![image](https://github.com/Vexcenot/-Middle-Mann/assets/40475772/61bfe53c-e1ee-48c2-9eba-af42a870a28f)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Resolution: 1920x1080
 - Controller: Dualshock 4

**Comment by TechnoSL** [comment]
pushed a very bandaid fix for this, please download this beta version and let me know if it fixes the taunt menu atleast being offscreen (i can't test tf2 with a controller very well as my settings are fucky)
https://github.com/TechnoSL/Middle-Mann/archive/refs/heads/master.zip

**Comment by LexHansenGuitar** [comment]
Yep 👍 it works
![image](https://github.com/Vexcenot/-Middle-Mann/assets/40475772/3f03f244-4100-439d-a559-a4fcff9fb9f4)
