### ISSUE TITLE
(small inconsistency) demoman charge meter's text formatting is inconsistent when compared to the other meters in other classes

### ISSUE THREAD

**Issue by fakesuu** [Vexcenot/-Middle-Mann#61]
i am obsessed with item meters

**Comment by TechnoSL** [comment]
go dl and check if the meter is still inconsistent https://github.com/TechnoSL/Middle-Mann/archive/refs/heads/beta.zip

**Comment by fakesuu** [comment]
![image](https://github.com/Vexcenot/-Middle-Mann/assets/129467529/b7d47105-14ce-4d20-8d79-45cf34818026)
fixed but now text is abbreviated

**Comment by TechnoSL** [comment]
lmk if this fixes this time

**Comment by fakesuu** [comment]
fixed tysm :)
