### ISSUE TITLE
Can't open community servers (linux)

### ISSUE THREAD

**Issue by ChildishGiant** [Vexcenot/-Middle-Mann#62]
When trying to open the community servers, nothing happens. I looked in the console to see if there's any errors but it's a tad white. On hud v14.9.1

[Screencast from 2023-08-17 00-53-13 (trimmed).webm](https://github.com/Vexcenot/-Middle-Mann/assets/13716824/5598e6b4-0613-4211-b275-98ba3913f706)

**Comment by TechnoSL** [comment]
anything else on your custom folder?

**Comment by ChildishGiant** [comment]
nothing else that should touch HUD stuff and I just removed them all anyway and tried and the issue is still there. I'm on linux native which might complicate things somehow (eg I've installed the fonts but some checkboxes are still funky)

**Comment by TechnoSL** [comment]
if the in-game console has issues it might? be an issue with [sourcescheme.res](https://github.com/Vexcenot/-Middle-Mann/blob/master/resource/sourcescheme.res), if you remove that and it ends up working i'll look into the file itself (it hasn't been touched ever since the hud got on github)

**Comment by ChildishGiant** [comment]
Hmm so I found [these people](https://www.teamfortress.tv/10582/white-console-and-sever-browser) having similar issues yonks ago ... I just verified the integrity of my install and it's fixed 🤷🏻‍♀️ maybe just funky tf2 magic, not an issue with this HUD.
