### ISSUE TITLE
Inconsistent Item Meter Spacing (This is just me being very nitpicky, don't feel obligated to work on this if it's unfeasible)

### ISSUE THREAD

**Issue by Quantum-Apple** [Vexcenot/-Middle-Mann#67]
I've found a few inconsistencies with the spacing between item meters. Not sure which ones are feasible to fix or if it's even intentional or not, but I'll just list all of the ones I've found here anyways. I understand how nitpicky this is, so please don't feel forced to change this. I've listed this purely as a matter of standardization. If moving around the meters makes things look worse, please just keep them as they are.

This appears to be the standard, the spacing seen most commonly. Not overlapping, very slightly separated.
![Screenshot (43)](https://github.com/Vexcenot/-Middle-Mann/assets/141591941/3fd4af9f-f7bf-471a-b2f9-72a4ba90e75a)

Pyro:

Thermal Thruster meter slightly more spaced than usual
![Screenshot (50)](https://github.com/Vexcenot/-Middle-Mann/assets/141591941/24c89c3a-2c4d-4b2c-9db4-5f3b5f12a5db)

Manmelter crit counter much more spaced than usual (Frontier Justice is also slightly more spaced than normal, picture shown later)
![Screenshot (48)](https://github.com/Vexcenot/-Middle-Mann/assets/141591941/b23a6628-568f-4b5d-b6b8-100fd448e135)

Demoman:

Sticky counter and charge meters slightly more spaced from the eyelander head counter
![Screenshot (53)](https://github.com/Vexcenot/-Middle-Mann/assets/141591941/fc2e3c89-695e-4391-ba38-8981b8fd70c3)
![Screenshot (44)](https://github.com/Vexcenot/-Middle-Mann/assets/141591941/2e56f85a-04a0-4a50-8613-0f158d790a95)

Engineer:

Pomson overlaps the metal counter
![Screenshot (46)](https://github.com/Vexcenot/-Middle-Mann/assets/141591941/7fc31024-f9b6-427b-8d95-3583dabc3641)

Frontier Justice crit counter slightly more spaced apart from metal counter
![Screenshot (47)](https://github.com/Vexcenot/-Middle-Mann/assets/141591941/9be7e7b2-c787-41ed-80af-a6df5260af12)

Spy:

Item meters touch instead of being slightly spaced (probably because spy has so many meters).
![Screenshot (52)](https://github.com/Vexcenot/-Middle-Mann/assets/141591941/0e9eadfc-bd65-4d75-a7e6-bf2c53394eda)

**Comment by TechnoSL** [comment]
i'll work on most of those soon, for spy it was also a bandaid fix for the sapper meter.

when it comes to any items that have crit meters (diamondback, front. justice and things of the sort i didn't bother messing with them too much)

**Comment by TechnoSL** [comment]
> Pyro:
> 
> Thermal Thruster meter slightly more spaced than usual ![Screenshot (50)](https://user-images.githubusercontent.com/141591941/261217946-24c89c3a-2c4d-4b2c-9db4-5f3b5f12a5db.png)
fixed in next pull request
> Manmelter crit counter much more spaced than usual (Frontier Justice is also slightly more spaced than normal, picture shown later) ![Screenshot (48)](https://user-images.githubusercontent.com/141591941/261218140-b23a6628-568f-4b5d-b6b8-100fd448e135.png)
this is due to both the manmelter and frontier justice item meters both using `huditemeffectmeter_engineer.res` as the file to take values from, same thing as back in #50 where i fix one or break the other. 

> Demoman:
> 
> Sticky counter and charge meters slightly more spaced from the eyelander head counter ![Screenshot (53)](https://user-images.githubusercontent.com/141591941/261219426-fc2e3c89-695e-4391-ba38-8981b8fd70c3.png) ![Screenshot (44)](https://user-images.githubusercontent.com/141591941/261219452-2e56f85a-04a0-4a50-8613-0f158d790a95.png)
i don't notice a spacing difference, if you mean the stickybomb charge counter, that's intended.

> Engineer:
> 
> Pomson overlaps the metal counter ![Screenshot (46)](https://user-images.githubusercontent.com/141591941/261219871-7fc31024-f9b6-427b-8d95-3583dabc3641.png)
> 
> Frontier Justice crit counter slightly more spaced apart from metal counter ![Screenshot (47)](https://user-images.githubusercontent.com/141591941/261219976-9be7e7b2-c787-41ed-80af-a6df5260af12.png)
both fixed

> Spy:
> 
> Item meters touch instead of being slightly spaced (probably because spy has so many meters). ![Screenshot (52)](https://user-images.githubusercontent.com/141591941/261220055-0e9eadfc-bd65-4d75-a7e6-bf2c53394eda.png)
mostly an after effect of trying to fix #42, i'd have to do a lot more fucky stuff to fix it properly, but on hindsight i'll swap the sapper and diamondback crits meter

**Comment by Quantum-Apple** [comment]
I don't know what exactly happened, but the latest update made the scout primary and secondary meters overlap. I was able to fix this by changing the ypos of the scout secondary res files from 81 -> 79. Not sure what caused the issue, maybe the soda popper res file being switched to use #base?

Before modification
![Screenshot (58)](https://github.com/Vexcenot/-Middle-Mann/assets/141591941/049cf980-b760-4c08-a5cb-e446cab32167)

After modification
![Screenshot (59)](https://github.com/Vexcenot/-Middle-Mann/assets/141591941/bfa89f51-cf1d-44b4-b26b-c06b469094de)

Has the added bonus of making the shield meter not overlap with the vaccinator resistances
![Screenshot (60)](https://github.com/Vexcenot/-Middle-Mann/assets/141591941/04518772-4a1b-49ec-9f68-005ab876beac)

**Comment by Quantum-Apple** [comment]
> i don't notice a spacing difference, if you mean the stickybomb charge counter, that's intended.

Soldier:
![Soldier](https://github.com/Vexcenot/-Middle-Mann/assets/141591941/616f7b29-0131-47da-9bbe-dfb2ab5c92d9)

Heavy:
![Heavy](https://github.com/Vexcenot/-Middle-Mann/assets/141591941/6a9596a8-f080-4d1a-acdb-f819ce17b757)

Sniper:
![Sniper](https://github.com/Vexcenot/-Middle-Mann/assets/141591941/88c4ef4b-dc3a-43dd-adc6-99be0301af16)

Demoman:
![Demoman](https://github.com/Vexcenot/-Middle-Mann/assets/141591941/1220cebc-7497-4bce-80e9-8a45e7874106)
![Shield](https://github.com/Vexcenot/-Middle-Mann/assets/141591941/12bde2b6-2f22-4842-873b-9c2d683ea6b0)



It's a very slight difference, but the demoman stuff is slightly more spaced apart

**Comment by TechnoSL** [comment]
> 

fixed

**Comment by Quantum-Apple** [comment]
Is it not possible to raise both the frontier justice/manmelter meters and just adjust the metal meter accordingly?

**Comment by TechnoSL** [comment]
> Is it not possible to raise both the frontier justice/manmelter meters and just adjust the metal meter accordingly?

https://github.com/Vexcenot/-Middle-Mann/pull/71/commits/e5fbbfce9d7e6580a95381e71d9674466e92d1c7#diff-73b788828f9ede9a59b67c38282f10690d4dbccdd5f2189db7d9e948440cc764 i'm doing the reverse

as for pyro i'm moving the jetpack to where the manmelter crits is and moving the mmmph meter down as we speak

**Comment by Quantum-Apple** [comment]
Ah crap, just found a few item meters overlapping with the mvm bomb icon. I'll create a seperate issue for those.

**Comment by TechnoSL** [comment]
> Ah crap, just found a few item meters overlapping with the mvm bomb icon. I'll create a seperate issue for those.

feel free to, i'll probably try to rework the mvm bomb stuff to be _slightly_ smaller to fix this without compromising too much (about 10% smaller)

**Comment by Quantum-Apple** [comment]
Alright, issue posted. #72

**Comment by Quantum-Apple** [comment]
You did not update the gas meter

![Screenshot (74)](https://github.com/Vexcenot/-Middle-Mann/assets/141591941/4ee74431-86dd-4b59-ba13-94bc23cee91c)

**Comment by TechnoSL** [comment]
> You did not update the gas meter
> 
> ![Screenshot (74)](https://user-images.githubusercontent.com/141591941/261503498-4ee74431-86dd-4b59-ba13-94bc23cee91c.png)

<html>
<body>


huditemeffectmeter.res | Charge meter for: Sandman / Wrap Assassin / Sandvich / Spy Watches / Jarate / Razorback / Cleaner's Carbine / Soldier Banners / Gas Passer
-- | --


<br class="Apple-interchange-newline">
</body>
</html>

i would have to rework the mmph and manmelter meters, i'll commit a hotfix directly to master after i fix #72

**Comment by Quantum-Apple** [comment]
Unfortunate, but very understandable. I hope that's all of the major issues fixed.
