### ISSUE TITLE
[Suggestion] Backpack keyboard hotkey indicators + expand functionality

### ISSUE THREAD

**Issue by Quantum-Apple** [Vexcenot/-Middle-Mann#69]
Middle Mann has A and D hotkeys to change pages in the backpack, which is great. However, there is no indicator in the backpack that this feature exists. I suggest doing something similar to eve hud, where the arrow buttons on screen also show A and D as an indicator of the hotkey, giving people new to custom huds an indication of this backpack feature.

If possible, it would also be nice if these hotkeys applied to other areas such as the weapon and cosmetic selection, smelting and crafting, and the mann co store.

e.v.e backpack
![Screenshot (54)](https://github.com/Vexcenot/-Middle-Mann/assets/141591941/8f257d88-d3e8-4d04-a5fb-3c77a8c3fc6d)

Middle Mann backpack
![Screenshot (56)](https://github.com/Vexcenot/-Middle-Mann/assets/141591941/ea500839-526d-4112-beca-74122081e9ce)

**Comment by TechnoSL** [comment]
for indicators its a matter of changing the label from arrows to a and d respectively

**Comment by Quantum-Apple** [comment]
Unfortunately, I have little experience with custom huds, so I can't really help with that. e.v.e hud (https://gamebanana.com/mods/26852) does have those hot keys for crafting and cosmetics selectection if that helps. 


![Screenshot (79)](https://github.com/Vexcenot/-Middle-Mann/assets/141591941/97af02c7-190c-4e42-8671-b1ee829c2347)
![Screenshot (80)](https://github.com/Vexcenot/-Middle-Mann/assets/141591941/dca6aca7-9487-4445-92a8-44487fd57c54)

**Comment by TechnoSL** [comment]
added as of #103, closing (might not be in crafting panel though, sorry.)
