### ISSUE TITLE
[Feature Request] Press E in class select to open weapon selection

### ISSUE THREAD

**Issue by Quantum-Apple** [Vexcenot/-Middle-Mann#70]
I used to use e.v.e hud and this was a feature I really enjoyed. In the class select screen, just by hovering over a class and pressing E, I was able to open the class's weapon select screen. My request to add this feature to middle mann as well (as long as it isn't too difficult of course).

e.v.e hud's class select screen
![Screenshot (55)](https://github.com/Vexcenot/-Middle-Mann/assets/141591941/ef4e2c7e-0fab-49e5-b67a-05ca1ee917dd)

**Comment by TechnoSL** [comment]
i have no clue on how to do that yet, but i'll plan on it whenever work starts being made on the class selection

**Comment by Quantum-Apple** [comment]
Probably best to change this and #69 labels to enhancements instead of bug. Either I'm being dumb and can't figure out how to change the label myself, or it's just not possible for me to change it.

**Comment by TechnoSL** [comment]
> Probably best to change this and #69 labels to enhancements instead of bug. Either I'm being dumb and can't figure out how to change the label myself, or it's just not possible for me to change it.

use the suggestion template next time, just added that for stuff like that

**Comment by TechnoSL** [comment]
added as of #103, closing
