### ISSUE TITLE
Item meter overlaps with MvM bomb icon

### ISSUE THREAD

**Issue by Quantum-Apple** [Vexcenot/-Middle-Mann#72]
A few item meters overlap with the bomb icon in mvm, I've listed the ones I've found.

Manmelter
![Screenshot (66)](https://github.com/Vexcenot/-Middle-Mann/assets/141591941/64544678-6aa0-4d3f-99e8-7615e3cbc12d)

Shields
![Screenshot (68)](https://github.com/Vexcenot/-Middle-Mann/assets/141591941/c6101d18-5b64-4584-a76f-a0d3dbca8e22)

Stickies
![Screenshot (73)](https://github.com/Vexcenot/-Middle-Mann/assets/141591941/548e26ca-77b4-4ebf-85f3-aa569a9b9519)

Frontier Justice
![Screenshot (71)](https://github.com/Vexcenot/-Middle-Mann/assets/141591941/36d12d83-6638-4322-b4f0-a76e982d113e)

Pomson:
![Screenshot (72)](https://github.com/Vexcenot/-Middle-Mann/assets/141591941/7937e09e-e1bf-4544-98f0-ad3461c9b178)

Vita Saw:
![Screenshot (69)](https://github.com/Vexcenot/-Middle-Mann/assets/141591941/05873222-00e4-4f4d-909e-9b7a480b92cc)

**Comment by TechnoSL** [comment]
as i said in #67, i'll probably work on _trying_ to make the mvm bomb carrier hud smaller (moving it down most likely) to see if i don't have to touch item meter code again

**Comment by Quantum-Apple** [comment]
Sorry if I wasn't clear in the previous post, but I downloaded the latest version from github and the issue is that the gas meter overlaps with the phlog meter.

**Comment by TechnoSL** [comment]
preview of fix (there's still a _really really_ tiny overlap, but i don't want to move it even further down than it needs to)
![image](https://github.com/Vexcenot/-Middle-Mann/assets/41777800/947f5954-6875-44ca-8627-e283fd33a3d2)

**Comment by TechnoSL** [comment]
this should be every meter-mvm overlap related fix. i think, i'll work on other stuff now
