### ISSUE TITLE
Status effects not centered

### ISSUE THREAD

**Issue by Quantum-Apple** [Vexcenot/-Middle-Mann#75]
From https://gamebanana.com/posts/11047637

Sorry for the flood of issues lol.

Status effects are not centered. Also, when multiple effects are active, the icons are only added to the right, looking a bit strange to me (although I don't even know if this is possible to change)

Escape Plan
![Screenshot (75)](https://github.com/Vexcenot/-Middle-Mann/assets/141591941/45ffc8ce-f81f-4fa1-833d-974522be0605)

Escape Plan + Base Jumper
![Screenshot (76)](https://github.com/Vexcenot/-Middle-Mann/assets/141591941/b7ec2a03-4868-4ca1-87ed-2e9170d61dfc)

Many more effects (applied with cheats in screenshot but theoretically possible in real games)
![Screenshot (77)](https://github.com/Vexcenot/-Middle-Mann/assets/141591941/c6342d81-3fc0-407d-9683-fd9311b907da)

**Comment by TechnoSL** [comment]
i'll probably move it back to where it was originally, vexcenot messed with that file like 15 trillion times and it could be any commit to it that originally caused it
https://github.com/Vexcenot/-Middle-Mann/commits/master/resource/ui/hudplayerhealth.res
