### ISSUE TITLE
Stickybomb counter's text in the HUD isn't centered

### ISSUE THREAD

**Issue by fakesuu** [Vexcenot/-Middle-Mann#77]
**Describe the Issue**
Stickybomb counter's text in the HUD isn't centered like it should be, since all the counter's texts are properly centered; You could move all of them slightly to te right or only change the sticky counter to the center

Also the stickybomb icon disappearing when there are none placed a intentional change? I think it's kinda confusing and unnecessary, since it's the only icon that does this (recommended this HUD to a newbie friend and he was also confused af)

**To Reproduce (gamemode/loadout etc)**
1. Join any gamemode
2. Equip any stickybomb launcher
3. Cry

**Expected behavior**
Stickybomb counter's text should be centered like all the counter's texts

**Screenshots**
![image](https://github.com/Vexcenot/-Middle-Mann/assets/129467529/356e5b39-1ae3-4e61-ac88-98ac8d59a1bc)
![image](https://github.com/Vexcenot/-Middle-Mann/assets/129467529/7eab14ca-e270-44bf-b0e9-d3086d0428ba)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Resolution: 1920x1080 (16:9)

**Comment by fakesuu** [comment]
also sorry for bed english my country is'nt america

**Comment by TechnoSL** [comment]
> Also the stickybomb icon disappearing when there are none placed a intentional change? I think it's kinda confusing and unnecessary, since it's the only icon that does this (recommended this HUD to a newbie friend and he was also confused af)
yes
