### ISSUE TITLE
Mann Co Store overlapping elements

### ISSUE THREAD

**Issue by Quantum-Apple** [Vexcenot/-Middle-Mann#83]
The spy class icon is slightly cut off and the support community map makers button overlaps with the checkout button. These issues are present on the default hud as well since the layout is the same (I guessing it just hasn't been worked on yet), so I'm not sure if these are fixable.

Windows 11
2560 x 1440

![mann co store](https://github.com/Vexcenot/-Middle-Mann/assets/141591941/c862332d-25a9-4443-b4ed-a6be6c4ee761)

**Comment by TechnoSL** [comment]
won't fix, it's the default hud's store screen and the only things that are modified outside the game are the inventory and loadout screens
