### ISSUE TITLE
Status Effect Overlap with damage dealt number

### ISSUE THREAD

**Issue by Quantum-Apple** [Vexcenot/-Middle-Mann#84]
The number that shows above the player model when you deal or heal damage overlaps with any status effects you have,

Escape Plan + Conch regen
![Screenshot (82)](https://github.com/Vexcenot/-Middle-Mann/assets/141591941/484ea1e7-d286-4a0e-adac-c4f0cccbfda0)

Escape Plan + Conch regen + buff banner effect
![Screenshot (83)](https://github.com/Vexcenot/-Middle-Mann/assets/141591941/118e2d5a-1757-4d5a-9131-80ad033730cc)

**Comment by TechnoSL** [comment]
i'll probably just move the status effects up since i find it fine for the damage to be there, either that or a customization to put it under ammo

**Comment by TechnoSL** [comment]
fix preview:
![image](https://github.com/Vexcenot/-Middle-Mann/assets/41777800/0249d711-27c6-4902-95b9-916f265ae4f1)
