### ISSUE TITLE
MinHud messes up teammate/enemy/spy-disguised-as health ui

### ISSUE THREAD

**Issue by KaimTime** [Vexcenot/-Middle-Mann#85]
**Describe the Issue**
When mousing over teammates & enemies as well as looking at the enemy disguised as ui on minimal hud mode their health numbers text, shadow & health cross are misaligned.

**To Reproduce (gamemode/loadout etc)**
Go to advanced options & turn on minimal hud to reproduce.

Screenshots:
https://a.l3n.co/i/VlGv5a.png (teammate 1)
https://c.l3n.co/i/VlGFWK.png (teammate 2)
https://lensdump.com/i/VlGU9Z (spy disguise ui broken)
https://c.l3n.co/i/VlGXGm.png (enemies)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Resolution: 1920x1080

**Comment by TechnoSL** [comment]
this hud is meant to be used with minmode disabled, it's even forced if you use the hud

no plans to fix until i make a minmode update

**Comment by KaimTime** [comment]
> this hud is meant to be used with minmode disabled, it's even forced if you use the hud:
> 
> https://github.com/Vexcenot/-Middle-Mann/blob/609c3cb8028b71d1446d83b53020eb08a86bed8f/cfg/valve.rc#L15
> 
> no plans to fix until i make a minmode update (not very soon mind you)

oh! gotcha, I got confused by the "minmode toggle" feature being listed on the mastercomfig page then.
