### ISSUE TITLE
ui items skewed to the left or right 

### ISSUE THREAD

**Issue by jepminer** [Vexcenot/-Middle-Mann#86]
HUD looks great but I'm having some weird ui position issues, not sure if I've done anything wrong or if it just doesn't like my game for some reason
![20230822221331_1](https://github.com/Vexcenot/-Middle-Mann/assets/33632057/976b6873-e151-485b-a604-d4fb60de148c)
![20230822220540_1](https://github.com/Vexcenot/-Middle-Mann/assets/33632057/7b68db81-cd8d-4d07-96e6-e384f9121446)
![20230822220636_1](https://github.com/Vexcenot/-Middle-Mann/assets/33632057/36eb126a-ceb6-4fd1-9e51-85a0fa44f743)
if it helps I'm playing on a 4k monitor at 1440p in the settings.

also the chat gets in the way of voting
![20230823014354_1](https://github.com/Vexcenot/-Middle-Mann/assets/33632057/9630270e-76c8-4c23-88cb-61ced6801b47)

**Comment by TechnoSL** [comment]
any specific customizations? some of the customizations in the hud are meant to be used only with the sidebar customization, aka the folders that have "corners" in parentheses

**Comment by jepminer** [comment]
Reinstalling did fit the model being in the wrong place, is the repsawn text meant to be off to the right like that? And that also didn't fix the chat obscuring the voting system (that could be fixed by moving it higher)

**Comment by TechnoSL** [comment]
> Reinstalling did fit the model being in the wrong place, is the respawn text meant to be off to the right like that? 

yes
>And that also didn't fix the chat obscuring the voting system (that could be fixed by moving it higher)

ill fix it later
