### ISSUE TITLE
ConTracker not properly working/freezes.

### ISSUE THREAD

**Issue by JosNai** [Vexcenot/-Middle-Mann#94]
**Describe the Issue**
Whenever I either use my "USE" key to open the ConTracker or click on it's designated button in the main menu it opens but freezes and never shows it's actual interface. The animated static effect is still animated but the actual ConTracker wont display the contracts. Clicking blindly I still hear the interface sound effects meaning that it's for some reason not displaying properly but still works.

**To Reproduce**
1. In any way open the ConTracker
2. See Issue

**Expected behavior**
The Contracker to exit it's startup animation an display the contracts.

**Screenshots**
[Screenshot](https://media.discordapp.net/attachments/532891699865976855/1145330947412205589/Skarmavbild_2023-08-27_kl._14.15.34.png?width=922&height=519)

**Desktop (please complete the following information):**
 - OS: MacOS 10.14.6 (Latest TF2 Supported Mac Verision)
 - Resolution: 1344 x 756 (16:9) (Issue still appears on all resolutions)

**Comment by TechnoSL** [comment]
that's weird, this might be a macos-specific issue? it works fine on my end in windows 
![image](https://github.com/Vexcenot/-Middle-Mann/assets/41777800/98984250-653a-479f-8396-6a9d3e40c446)

**Comment by JosNai** [comment]
This issue was somehow fixed by me just redownloading the latest release. Not really sure why it was happening but it works now.

**Comment by TechnoSL** [comment]
great
