### ISSUE TITLE
MvM - Large FPS drops using weapons that do frequent damage events

### ISSUE THREAD

**Issue by SinisterPx** [Vexcenot/-Middle-Mann#95]
**Describe the Issue**
When using the HUD in MVM, dealing damage with a weapon that generates frequent damage events (such as the flamethrower or Medic projectile shield), framerate drops to < 1fps. Appears to be a known issue with custom HUDs which has been documented at length by sigsegv here: https://reddit.com/r/tf2/s/zwyo2OtzUz

**To Reproduce (gamemode/loadout etc)**
1. Go to any MVM mission
2. Equip any class/weapon that deals frequent damage events. Medic with the projectile shield is the most apparent example
3. Play on any MVM map and try to damage any number of enemies with the shield
4. See Issue

**Expected behavior**
Ordinarily these damage events do not generate any sort of lag, however it appears that certain values stored in `Event DamagedPlayer` triggering rapidly is causing the performance issues

**Desktop (please complete the following information):**
 - OS: Windows 10 - Version 22H2 - Build 19045.3324
 - Resolution: 2560 x 1440

**Comment by TechnoSL** [comment]
what version of the hud are you using? i fixed this exact issue 15 years ago on this commit but i wouldnt be surprised if vexcenot reimplemented the bug again https://github.com/Vexcenot/-Middle-Mann/commit/bbcd2ef9512fb4ad8ca016c92f2952253ed81e8f

**Comment by SinisterPx** [comment]
Ah I believe I'm using a slightly earlier version. I'll install the newer version and report back

**Comment by TechnoSL** [comment]
mfw still waiting on a report so i can close this bug report

**Comment by SinisterPx** [comment]
My bad. Newer version works fine. You can close the bug
