### ISSUE TITLE
Demoman's shield charge and sticky count are not showing up after latest update

### ISSUE THREAD

**Issue by THE-EXP** [Vexcenot/-Middle-Mann#96]
**Describe the Issue**
Demoman's shield charge and sticky count don't show up after latest update [f807f1f](https://github.com/Vexcenot/-Middle-Mann/commit/f807f1f7bdfceee1293b2dfde926d98a615bacb8), possibly even older for when customizations were added

**To Reproduce (gamemode/loadout etc)**
1. Get latest GitHub version of the hud
2. load into the game(easiest and fastest way is to type `map itemtest` into the console)
3. spawn as a demoman, equip either a shield or any stickybomb launcher
4. See the Issue

**Expected behavior**
Demoman's shield charge and sticky count should show up in the center(presumably somewhere under the crosshair)

**Desktop (please complete the following information):**
 - OS: Windows 10 x64
 - Resolution (Aspect Ratio): 1440x900 16:10

**TF2 Specific Info (please complete the following information):**
 - HUD Version (either commit # or release version): [f807f1f](https://github.com/Vexcenot/-Middle-Mann/commit/f807f1f7bdfceee1293b2dfde926d98a615bacb8)
 - Customizations Applied (if any): Modified Centered dammage accumulator(Last Damage -> Centered)
 - Other Mods (only applies if you have mods in `tf/custom`): None that interfere with hud(i.e audio mods and model changers)

**Comment by TechnoSL** [comment]
do you have any specific customizations? this might be less due to item meters being bugged and more due to not testing stuff in 16:10 (might work on that soon

**Comment by THE-EXP** [comment]
A little update, meters DO show up, except for demoman's shield charge for some reason(stickies work fine(except the counter for stickies), but why the bottom right corner for the launcher charge?)

**Comment by TechnoSL** [comment]
can i have a screenshot?

**Comment by THE-EXP** [comment]
![20230830222248_1](https://github.com/Vexcenot/-Middle-Mann/assets/105677206/c64978fd-35db-49ec-a36b-713cd069e43c)
![20230830222300_1](https://github.com/Vexcenot/-Middle-Mann/assets/105677206/e0b2a5bc-b468-466f-88c7-32626c989d71)
Here are both with stickes and with shield
![20230830222352_1](https://github.com/Vexcenot/-Middle-Mann/assets/105677206/c061ab08-c741-4eb9-b3ca-6989888bc66b)
And scout's mad milk to show that the meters actually work

**Comment by THE-EXP** [comment]
Also taunts menu gets cutoff:
![20230830223609_1](https://github.com/Vexcenot/-Middle-Mann/assets/105677206/4de075b1-39bd-4b52-b04d-3bd1e5502570)

**Comment by TechnoSL** [comment]
> ![20230830222248_1](https://user-images.githubusercontent.com/105677206/264451027-c64978fd-35db-49ec-a36b-713cd069e43c.jpg) ![20230830222300_1](https://user-images.githubusercontent.com/105677206/264451035-e0b2a5bc-b468-466f-88c7-32626c989d71.jpg) Here are both with stickes and with shield ![20230830222352_1](https://user-images.githubusercontent.com/105677206/264451176-c061ab08-c741-4eb9-b3ca-6989888bc66b.jpg) And scout's mad milk to show that the meters actually work

seems to be an issue with https://github.com/Vexcenot/-Middle-Mann/blob/master/resource/ui/HudDemomanPipes.res, don't know why that file would be fucking up for you despite having minimal changes, do you happen to have minmode turned on or something?

**Comment by THE-EXP** [comment]
Also ammo count on engineer
![20230830224808_1](https://github.com/Vexcenot/-Middle-Mann/assets/105677206/043e4d9f-c953-4498-b1dd-3f06dc646838)

**Comment by THE-EXP** [comment]
> seems to be an issue with [huddemomanpipes.res](https://github.com/Vexcenot/-Middle-Mann/blob/master/resource/ui/HudDemomanPipes.res), don't know why that file would be fucking up for you despite having minimal changes, do you happen to have minmode turned on or something? might be something fucking up there/ you might have a config forcing it on

Minmode is off and is not enforced

**Comment by TechnoSL** [comment]
if so, at this point i have no clue, you might have some mods that conflict with the hud since in my end everything you reported works fine for me (took these screenshots just now in 1440x900 16:10)
![image](https://github.com/Vexcenot/-Middle-Mann/assets/41777800/18dce116-a634-4f9d-ae2e-eb43e6113758)
![image](https://github.com/Vexcenot/-Middle-Mann/assets/41777800/7bbf7c45-0cec-4e55-b16f-0695646c6a29)
![image](https://github.com/Vexcenot/-Middle-Mann/assets/41777800/3e33e5b1-8ee2-4a67-b84c-cb8bc32dc172)
![image](https://github.com/Vexcenot/-Middle-Mann/assets/41777800/38fb63c2-6293-4c5a-aa4c-f625e2e70f3e)

https://rc4322.s-ul.eu/LOXByyoZ feel free to try this one last time, it's my own clean dev build

**Comment by THE-EXP** [comment]
Still a no unfortunately, i'll verify the files and see if that helps, otherwise i might delete some things

**Comment by TechnoSL** [comment]
> (+ the hitmarkers addon)

might have found the culprit, can you remove the addon and check if stuff works again?

**Comment by THE-EXP** [comment]
> > (+ the hitmarkers addon)
> 
> might have found the culprit, can you remove the addon and check if stuff works again?

Yup, that's what it was
Unfortunately, i like the hitmarkers

**Comment by TechnoSL** [comment]
unfortunate, but that's sadly outside of my power, i only work on the hud, you'll have to take it up with @Vexcenot on that front.

will be closing the bug report now, thanks for the report.
