### ISSUE TITLE
Master Hitmarkers deletes the ammo counter

### ISSUE THREAD

**Issue by The-Brickler** [Vexcenot/-Middle-Mann#98]
**Describe the Issue**
Everything else looks fine, but the whole ammo counter is straight up missing.

**To Reproduce (gamemode/loadout etc)**
Install Master Hitmarkers and Middle Mann
It happens on every map, every class, every weapon

**Expected behavior**
There should be an ammo count

**Screenshots**
![20230830144505_1](https://github.com/Vexcenot/-Middle-Mann/assets/11480598/9aa7f818-4584-4b72-a7db-b5a8529a25bd)
![20230830145603_1](https://github.com/Vexcenot/-Middle-Mann/assets/11480598/c8fcaa97-9fa0-492a-b189-cc2415018943)

**Desktop (please complete the following information):**
 - OS: Linux Manjaro 23.0.0
 - Resolution (Aspect Ratio): 1920x1080 (16:9)

**TF2 Specific Info (please complete the following information):**
 - HUD Version (either commit # or release version): v15.1.1
 - Customizations Applied (if any): N/A
 - Other Mods (only applies if you have mods in `tf/custom`): 
      - Animated Loading Screen
      - Dyslexic Crosshair
      - Master Hitmarkers
      - Custom hit and killsound

**Comment by The-Brickler** [comment]
After a bit of testing, this is caused by having [Master Hitmarkers](https://gamebanana.com/mods/460476) at the same time as Middle Mann

**Comment by TechnoSL** [comment]
outside of my control sadly, scream at @Vexcenot to fix master hitmarkers
