### ISSUE TITLE
Ubercharge value drop shadow is inconsistent

### ISSUE THREAD

**Issue by Bunslinger** [Vexcenot/-Middle-Mann#99]
When using any medigun, the numerical value of the ubercharge in the bottom right seems to have a drop shadow, but it's not the same color nor is it the same position that the ammo counter uses, resulting in an odd inconsistency between the two.

**Comment by TechnoSL** [comment]
fixing this "bug" would break the vaccinator/viceversa, no other choice.

**Comment by Bunslinger** [comment]
oh well, thanks for the reply!
